### ISSUE TITLE
I want to expand all groups initially with focus on first item ?

### ISSUE THREAD

**Issue by aZyreTech** [Android-Tutorials-Hub/expandable-list-view-tutorial#1]
I am trying to expand all groups initially and i am getting that.
But the problem is when my all groups are expanded focus goes to last item. I want to expand all groups with first item focusable.
How to do that ?

**Comment by lalit-vasan** [comment]
Hi,

Use the smoothScrollToPosition(pos) function to scroll to the position you want to scroll.
Like
`expandableListView.smoothScrollToPosition(<position>);`

In your case 
`expandableListView.smoothScrollToPosition(0);`

Hope this may help you, Feel free to ask

**Comment by aZyreTech** [comment]
thanks
